import { readRuminations } from "@/lib/libraryReader";
import type { RuminationEntry } from "@/lib/libraryReader";
import { RuminationCard } from "@/components/RuminationCard";

export const revalidate = 60;

export default function RuminationsPage() {
    let entries: RuminationEntry[] = [];
    let error: string | null = null;

    try {
        entries = readRuminations();
    } catch (e) {
        error = e instanceof Error ? e.message : "Failed to load ruminations";
    }

    // Sort: active first, then draft, resolved, archived; within each by filedAt desc
    const ORDER: RuminationEntry["status"][] = ["active", "draft", "resolved", "archived"];
    entries = [...entries].sort((a, b) => {
        const os = ORDER.indexOf(a.status) - ORDER.indexOf(b.status);
        if (os !== 0) return os;
        return (b.filedAt ?? "").localeCompare(a.filedAt ?? "");
    });

    return (
        <div className="mx-auto max-w-4xl px-6 py-10">
            <div className="mb-8">
                <h1 className="text-3xl font-bold tracking-tight">Rumination Tracker</h1>
                <p className="mt-1 text-neutral-500">
                    Novel hypotheses and lateral syntheses generated by openclaw
                </p>
            </div>

            {error && (
                <div className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
                    <strong>Error loading ruminations:</strong> {error}
                </div>
            )}

            {entries.length === 0 && !error && (
                <p className="text-sm text-neutral-500">No rumination files found.</p>
            )}

            <ul className="space-y-5">
                {entries.map((entry) => (
                    <RuminationCard key={entry.slug} entry={entry} />
                ))}
            </ul>
        </div>
    );
}
