import { readRuminations } from "@/lib/libraryReader";
import type { RuminationEntry, RuminationStatus } from "@/lib/libraryReader";
import { RuminationCard } from "@/components/RuminationCard";
import { RuminationStatusTabs } from "@/components/RuminationStatusTabs";

export const revalidate = 60;

interface PageProps {
    searchParams: Promise<{ status?: string }>;
}

export default async function RuminationsPage({ searchParams }: PageProps) {
    const { status } = await searchParams;

    let entries: RuminationEntry[] = [];
    let error: string | null = null;

    try {
        entries = readRuminations();
    } catch (e) {
        error = e instanceof Error ? e.message : "Failed to load ruminations";
    }

    const counts: Record<RuminationStatus, number> = {
        draft: 0,
        active: 0,
        validated: 0,
        refuted: 0,
        stale: 0,
    };

    for (const entry of entries) {
        counts[entry.status] += 1;
    }

    let filtered = entries;
    if (status && status in counts) {
        filtered = entries.filter((entry) => entry.status === status);
    }

    // Sort newest first by filedAt
    filtered = [...filtered].sort((a, b) => {
        const byDate = b.filedAt.localeCompare(a.filedAt);
        if (byDate !== 0) return byDate;
        return a.title.localeCompare(b.title);
    });

    return (
        <div className="mx-auto max-w-4xl px-6 py-10">
            <div className="mb-8">
                <h1 className="text-3xl font-bold tracking-tight">Rumination Tracker</h1>
                <p className="mt-1 text-neutral-500">
                    Novel hypotheses and lateral syntheses generated by openclaw
                </p>
            </div>

            <RuminationStatusTabs counts={counts} />

            {error && (
                <div className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
                    <strong>Error loading ruminations:</strong> {error}
                </div>
            )}

            {filtered.length === 0 && !error && (
                <p className="text-sm text-neutral-500">No rumination files found.</p>
            )}

            <ul className="space-y-5">
                {filtered.map((entry) => (
                    <RuminationCard key={entry.slug} entry={entry} />
                ))}
            </ul>
        </div>
    );
}
